spring:
  datasource:
    # MySQL DB 연결
    url: jdbc:mysql://localhost:3306/studyspot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET:your-very-long-secret-key-that-is-at-least-32-bytes-studyspot}
  access-token-expiration: 3600000

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}